/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PayableInterface extends Interface {
  getFunction(
    nameOrSignature: "getBalancec" | "getMsgvalue" | "getmsgSender"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBalancec",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMsgvalue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getmsgSender",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getBalancec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMsgvalue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getmsgSender",
    data: BytesLike
  ): Result;
}

export interface Payable extends BaseContract {
  connect(runner?: ContractRunner | null): Payable;
  waitForDeployment(): Promise<this>;

  interface: PayableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBalancec: TypedContractMethod<[_address: AddressLike], [bigint], "view">;

  getMsgvalue: TypedContractMethod<[], [bigint], "payable">;

  getmsgSender: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBalancec"
  ): TypedContractMethod<[_address: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMsgvalue"
  ): TypedContractMethod<[], [bigint], "payable">;
  getFunction(
    nameOrSignature: "getmsgSender"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
